on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-tag:
    name: Check Tag
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: "contains(github.ref, '-*')"
        run: exit 0
  upload-packages:
    name: Upload Packages
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        run: cargo build --release
      - name: Upload Packages
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/http-client.exe